# Generated by Django 5.2.7 on 2026-09-29 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountapprovalrequest'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='approval_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.accountapprovalrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('TICKET_CREATED', 'New ticket'), ('ASSIGNED', 'Ticket assigned'), ('COMMENT', 'New comment'), ('STATUS', 'Status changed'), ('MENTION', 'Mention'), ('DEADLINE', 'Deadline'), ('MEETING', 'Meeting'), ('VERIFICATION', 'Verification'), ('REOPENED', 'Ticket reopened'), ('ACCOUNT_APPROVAL', 'Account approval')], db_index=True, max_length=24),
        ),
    ]
