# Generated by Django 5.2.7 on 2026-09-29 07:34

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_normalize_director_designation'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], db_index=True, default='PENDING', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=accounts.models.approval_expiry_time)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_approval_requests', to='core.division')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_account_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='accounts_ac_status_d9ca6e_idx')],
            },
        ),
    ]
