# Generated by Django 5.2.7 on 2026-09-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_is_division_director'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='division',
            field=models.ForeignKey(help_text='Create a division first, then select the division this role belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='core.division'),
        ),
    ]
