# Generated by Django 5.2.7 on 2026-09-28 11:22

import django.db.models.deletion
import tickets.models
import tickets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ticket categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('color', models.CharField(default='#64748b', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ticket priorities',
                'ordering': ['-rank'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('WAITING', 'Waiting'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('color', models.CharField(default='#64748b', max_length=7)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'workflow statuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.division')),
            ],
            options={
                'ordering': ['division__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('expected_behavior', models.TextField(blank=True)),
                ('actual_behavior', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('module_page', models.CharField(blank=True, max_length=180)),
                ('browser_device', models.CharField(blank=True, max_length=255)),
                ('problem_identified_at', models.DateTimeField()),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identified_tickets', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tickets.ticket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.product')),
                ('related_tickets', models.ManyToManyField(blank=True, to='tickets.ticket')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
                ('requesting_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.division')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tickets', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketpriority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.workflowstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('technical_instructions', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_assignments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Requester visible'), ('INTERNAL', 'Internal IT only')], default='PUBLIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tickets.ticketcomment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.attachment_path, validators=[tickets.validators.validate_attachment])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketcomment')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('previous_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'ticket history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('VALID', 'Valid problem'), ('INVALID', 'Invalid problem'), ('NEED_INFO', 'Need more information'), ('DUPLICATE', 'Duplicate'), ('RESOLVED', 'Already resolved'), ('NOT_IT', 'Not an IT issue')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_reviews', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('VERIFIED', 'Problem resolved'), ('FAILED', 'Problem still exists')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='tickets.ticket')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requires_comment', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='status_transitions', to='accounts.role')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='tickets.workflowstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='tickets.workflowstatus')),
            ],
            options={
                'ordering': ['from_status__sort_order', 'to_status__sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('division', 'name'), name='unique_product_per_division'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['assigned_to', 'is_active'], name='tickets_tic_assigne_6af5c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketnumbersequence',
            constraint=models.UniqueConstraint(fields=('division', 'year'), name='unique_ticket_sequence'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requesting_division', 'status'], name='tickets_tic_request_39e189_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['current_assignee', 'status'], name='tickets_tic_current_f25e68_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['product', 'category'], name='tickets_tic_product_a7331d_idx'),
        ),
        migrations.AddConstraint(
            model_name='statustransition',
            constraint=models.UniqueConstraint(fields=('from_status', 'to_status'), name='unique_status_transition'),
        ),
    ]
