# Generated by Django 5.2.7 on 2026-09-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickettechnicalverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettechnicalverification',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Technical work approved'), ('RETURNED', 'Returned to responsible person')], max_length=10),
        ),
    ]
